import { Character } from "../Gameplay/Character";
import EnemyCharacter from "../Gameplay/EnemyCharacter";
import { House } from "../Gameplay/House";
import HouseEnemyController from "../Gameplay/HouseEnemyController";

interface Global {
    touchPos: cc.Vec2,
    startTouch: boolean,
    endGame: boolean,
    clickButtonSpawnWarior: boolean,
    enemyList: Character[],
    characterList: Character[],
    characterHouse: House,
    enemyHouse: House,
    Attack: string,
    Die: string,
    Hurt: string,
    Idle: string,
    Run: string,
    SpawnWarior: string,
    CheckPrice: string,
    UpdateCoin: string,
    CheckActiveGuide: string,
    RemoveFromList: string,
    ActiveText: string,
    StopGame: string,
    StartGame: string,
    CharacterHolder: cc.Node,
    CoinHolder: cc.Node,
    DieImageHolder: cc.Node,
    totalGold: number,
    totalFood: number,
    count: number,
    countEnemyDie: number,
    Win: cc.AudioClip,
    Lose: cc.AudioClip,
    Coin: cc.AudioClip,
    Click: cc.AudioClip,
    Unlock: cc.AudioClip,

}
let Global: Global = {
    touchPos: null,
    startTouch: false,
    endGame: false,
    clickButtonSpawnWarior: false,
    DieImageHolder: null,
    enemyList: [],
    characterList: [],
    characterHouse: null,
    enemyHouse: null,
    Attack: "Attack",
    Die: "Die",
    Hurt: "Hurt",
    Idle: "Idle",
    Run: "Run",
    SpawnWarior: "SpawnWarior",
    ActiveText: "ActiveText",
    CheckPrice: "CheckPrice",
    CheckActiveGuide: "CheckActiveGuide",
    RemoveFromList: "RemoveFromList",
    UpdateCoin: "CheckCoin",
    StopGame: "StopGame",
    StartGame: "StartGame",
    CharacterHolder: null,
    totalGold: 100,
    totalFood: 1,
    CoinHolder: null,
    count: 0,
    countEnemyDie: 0,
    Win: null,
    Lose: null,
    Coin: null,
    Click: null,
    Unlock: null,
};
export default Global;
export const eventDispatcher = new cc.EventTarget();